spring:
  flyway:
    url: "jdbc:postgresql://localhost:5000/accounts_db"
  r2dbc:
    url: "r2dbc:postgresql://localhost:5000/accounts_db"

server:
  port: 3000

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:3003/eureka"