spring:
  application:
    name: accounts

  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://accounts-postgres:35432/accounts_db
    user: postgres
    password: postgres

  r2dbc:
    url: r2dbc:postgresql://accounts-postgres:35432/accounts_db
    username: postgres
    password: postgres

server:
  port: 80
