spring:
  application:
    name: accounts

  r2dbc:
    url: r2dbc:postgresql://accounts-postgres:35432/accounts_db
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.data.r2dbc.core: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG

server:
  port: 80
