spring:
  flyway:
    url: "jdbc:postgresql://localhost:5001/cards_db"

  r2dbc:
    url: "r2dbc:postgresql://localhost:5001/cards_db"

server:
  port: 3002

eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:3003/eureka"
