spring:
  application:
    name: configserver

server:
  port: 80

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false