spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

server:
  port: 3004

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://localhost:3003/eureka"

management:
  endpoints:
    web:
      exposure:
        include: "*"